<?php
/**
 * @file
 * club_attendancepolicy.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function club_attendancepolicy_field_default_fields() {
  $fields = array();

  // Exported field: 'node-attendance_configuration-body'.
  $fields['node-attendance_configuration-body'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(
        0 => 'node',
      ),
      'field_name' => 'body',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '1',
      'type' => 'text_with_summary',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Describe the attendance rules in detail. These may be emailed to users if violations are detected.',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(
            'trim_length' => 600,
          ),
          'type' => 'text_summary_or_trimmed',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'body',
      'label' => 'Attendance Policy',
      'required' => 1,
      'settings' => array(
        'display_summary' => 1,
        'text_processing' => '1',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '20',
          'summary_rows' => 5,
        ),
        'type' => 'text_textarea_with_summary',
        'weight' => '4',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_appendpolicy'.
  $fields['node-attendance_configuration-field_appendpolicy'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_appendpolicy',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'Yes' => 'Yes',
          'No' => 'No',
        ),
        'allowed_values_function' => '',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => 'Yes',
        ),
      ),
      'deleted' => '0',
      'description' => 'If members are to receive a "Missed Meeting" message, should the system append the Attendance Policy to the email sent to them? This field has no effect if the "Missed Meeting" message is blank.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 11,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_appendpolicy',
      'label' => 'Append Policy',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '10',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_attendanceadmin'.
  $fields['node-attendance_configuration-field_attendanceadmin'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_attendanceadmin',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'email',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'email',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'If attendance reporting is to be emailed, enter one or more email addresses for the attendance administrators. For example, you might enter the Attendance Committee Chair\'s address and the Organization\'s President for each report.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'email',
          'settings' => array(),
          'type' => 'email_default',
          'weight' => 10,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_attendanceadmin',
      'label' => 'Attendance Admin Email',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'email',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'email_textfield',
        'weight' => '9',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_attendancerequirement'.
  $fields['node-attendance_configuration-field_attendancerequirement'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_attendancerequirement',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'number',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'number_integer',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'This field contains the percentage of total meetings required to maintain active member status. This is used for management reporting only.  Leave this field blank if you do not have a required attendance policy.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'number',
          'settings' => array(
            'decimal_separator' => '.',
            'prefix_suffix' => TRUE,
            'scale' => 0,
            'thousand_separator' => ' ',
          ),
          'type' => 'number_integer',
          'weight' => 7,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_attendancerequirement',
      'label' => 'Attendance Requirement',
      'required' => 0,
      'settings' => array(
        'max' => '100',
        'min' => '',
        'prefix' => '',
        'suffix' => '%',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => '6',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_chapter'.
  $fields['node-attendance_configuration-field_chapter'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_chapter',
      'field_permissions' => array(
        'type' => '2',
      ),
      'foreign keys' => array(
        'node' => array(
          'columns' => array(
            'target_id' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'target_id' => array(
          0 => 'target_id',
        ),
      ),
      'locked' => '0',
      'module' => 'entityreference',
      'settings' => array(
        'behaviors' => array(),
        'handler' => 'base',
        'handler_settings' => array(
          'behaviors' => array(
            'views-select-list' => array(
              'status' => 0,
            ),
          ),
          'sort' => array(
            'direction' => 'ASC',
            'field' => 'field_date:value',
            'property' => 'title',
            'type' => 'property',
          ),
          'target_bundles' => array(
            'chapter' => 'chapter',
          ),
        ),
        'handler_submit' => 'Change handler',
        'profile2_private' => FALSE,
        'target_type' => 'node',
      ),
      'translatable' => '0',
      'type' => 'entityreference',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'This is the chapter or club record that "owns" this attendance policy.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'link' => FALSE,
          ),
          'type' => 'entityreference_label',
          'weight' => 21,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_chapter',
      'label' => 'Chapter or Club',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '0',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_makeup_notation'.
  $fields['node-attendance_configuration-field_makeup_notation'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_makeup_notation',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => '* Makeups are not included in attendance totals',
        ),
      ),
      'deleted' => '0',
      'description' => 'Makeups are reports on all reports. If they are not counted in the totals, this field contains the report annotation reminder.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 20,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_makeup_notation',
      'label' => 'Makeup \'No Count\' Notation',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '10',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_makeup_policy'.
  $fields['node-attendance_configuration-field_makeup_policy'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_makeup_policy',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'Manual Update' => 'Manual Update',
          'Automatic' => 'Automatic',
        ),
        'allowed_values_function' => '',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => 'Manual Update',
        ),
      ),
      'deleted' => '0',
      'description' => 'If make-ups are allowed, they are treated in one of two ways: (1) Manual Update or (2) Automatic. <UL><LI>Manual Update: with this policy, regular meeting records are updated manually. For example, Rotary clubs allow a make-up two weeks before or two weeks after the missed meeting. In this case, the club secretary would pull up the list of meetings, select an appropriate missed meeting, and update its status from "Absent" to "Makeup". The Attendance Report will report this meeting in the Make-up column, not in the Absent column<LI>Automatic: with this policy, make-ups are added separately. The Attendance Report will report this meeting in the Make-Up column and will automatically reduce the Absent column by 1. </UL> The advantage of "Automatic" is that a full history of missed and made-up meetings is retained. The advantage of "Manual" is that you have control over make-up application.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 19,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_makeup_policy',
      'label' => 'Make-up Policy',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '9',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_makeupsallowed'.
  $fields['node-attendance_configuration-field_makeupsallowed'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_makeupsallowed',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'Yes' => 'Yes',
          'No' => 'No',
        ),
        'allowed_values_function' => '',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => 'Yes',
        ),
      ),
      'deleted' => '0',
      'description' => 'Whether or not makeups are allowed. The specific nature of makeups should be described in the "Attendance Policy".',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 4,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_makeupsallowed',
      'label' => 'Makeups Allowed',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '7',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_maximum_consecutive'.
  $fields['node-attendance_configuration-field_maximum_consecutive'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_maximum_consecutive',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'number',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'number_integer',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Some organizations may have an attendance policy that discourages consecutive missed meetings. For example, if some type of Board action is required after 5 consecutive missed meetings, enter "5". When the number of consecutive missed meetings reaches 6, an email is sent to the attendance contact email address(es). Leave this field blank if this is not part of your attendance policy.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'number',
          'settings' => array(
            'decimal_separator' => '.',
            'prefix_suffix' => TRUE,
            'scale' => 0,
            'thousand_separator' => ' ',
          ),
          'type' => 'number_integer',
          'weight' => 9,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_maximum_consecutive',
      'label' => 'Maximum Consecutive Missed Meetings',
      'required' => 0,
      'settings' => array(
        'max' => '',
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => '12',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_maximum_missed'.
  $fields['node-attendance_configuration-field_maximum_missed'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_maximum_missed',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'number',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'number_integer',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'This field contains the maximum number of allowable missed meetings before Board action is required. For example, if "Attendance Requirement" is 50%, and there are 26 meetings in the notification period, then this field should contain "13" -- that is, when 13 meetings are missed, some type of board action is required.  Leave this field blank if this is not part of your attendance policy.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'number',
          'settings' => array(
            'decimal_separator' => '.',
            'prefix_suffix' => TRUE,
            'scale' => 0,
            'thousand_separator' => ' ',
          ),
          'type' => 'number_integer',
          'weight' => 8,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_maximum_missed',
      'label' => 'Maximum Missed Meetings',
      'required' => 0,
      'settings' => array(
        'max' => '',
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => '11',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_maxmakeups'.
  $fields['node-attendance_configuration-field_maxmakeups'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_maxmakeups',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'number',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'number_integer',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'Maximum number of makeups allowed during this notification period. Enter "0" if there is no set maximum or if makeup meetings are not part of your attendance policy.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'number',
          'settings' => array(
            'decimal_separator' => '.',
            'prefix_suffix' => TRUE,
            'scale' => 0,
            'thousand_separator' => ' ',
          ),
          'type' => 'number_integer',
          'weight' => 5,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_maxmakeups',
      'label' => 'Maximum Number of Makeups allowed',
      'required' => 0,
      'settings' => array(
        'max' => '',
        'min' => '',
        'prefix' => '',
        'suffix' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'number',
        'settings' => array(),
        'type' => 'number',
        'weight' => '8',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_missed_subject'.
  $fields['node-attendance_configuration-field_missed_subject'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_missed_subject',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => 'We missed you!',
        ),
      ),
      'deleted' => '0',
      'description' => 'Missed Email Subject - the subject of the email reminder sent to people who miss meetings.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 18,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_missed_subject',
      'label' => 'Missed Subject',
      'required' => 1,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '8',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_missedyoumessage'.
  $fields['node-attendance_configuration-field_missedyoumessage'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_missedyoumessage',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'text_long',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => '(message)
--
(signature)',
        ),
      ),
      'deleted' => '0',
      'description' => 'Enter a message here if you want to send a "Missed You" message each time the member is absent. If you leave this field blank, no message will be sent. Be sure to include your email signature.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 6,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_missedyoumessage',
      'label' => 'Missed You Message',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '4',
        ),
        'type' => 'text_textarea',
        'weight' => '9',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_policy_date_range'.
  $fields['node-attendance_configuration-field_policy_date_range'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_policy_date_range',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'date',
      'settings' => array(
        'cache_count' => '4',
        'cache_enabled' => 0,
        'granularity' => array(
          'day' => 'day',
          'hour' => 0,
          'minute' => 0,
          'month' => 'month',
          'second' => 0,
          'year' => 'year',
        ),
        'profile2_private' => FALSE,
        'repeat' => '0',
        'timezone_db' => '',
        'todate' => 'required',
        'tz_handling' => 'none',
      ),
      'translatable' => '0',
      'type' => 'datetime',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'deleted' => '0',
      'description' => 'These fields contain the start and end date for this Attendance Policy. ',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'date',
          'settings' => array(
            'format_type' => 'long',
            'fromto' => 'both',
            'multiple_from' => '',
            'multiple_number' => '',
            'multiple_to' => '',
            'show_repeat_rule' => 'show',
          ),
          'type' => 'date_default',
          'weight' => 16,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_policy_date_range',
      'label' => 'Policy Date Range',
      'required' => 0,
      'settings' => array(
        'default_value' => 'now',
        'default_value2' => 'same',
        'default_value_code' => '',
        'default_value_code2' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'date',
        'settings' => array(
          'display_all_day' => 0,
          'increment' => '15',
          'input_format' => 'Y-m-d H:i:s',
          'input_format_custom' => '',
          'label_position' => 'above',
          'repeat_collapsed' => 0,
          'text_parts' => array(),
          'year_range' => '-3:+3',
        ),
        'type' => 'date_popup',
        'weight' => '3',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_status'.
  $fields['node-attendance_configuration-field_status'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_status',
      'foreign keys' => array(
        'tid' => array(
          'columns' => array(
            'tid' => 'tid',
          ),
          'table' => 'taxonomy_term_data',
        ),
      ),
      'indexes' => array(
        'tid' => array(
          0 => 'tid',
        ),
      ),
      'locked' => '0',
      'module' => 'taxonomy',
      'settings' => array(
        'allowed_values' => array(
          0 => array(
            'vocabulary' => 'member_status',
            'parent' => '0',
          ),
        ),
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'taxonomy_term_reference',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'If you are using the "Attendance Trigger" process, select one or more status values to include in the automated member inclusion.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'taxonomy',
          'settings' => array(),
          'type' => 'taxonomy_term_reference_link',
          'weight' => 22,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_status',
      'label' => 'Status Inclusions',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '5',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_test'.
  $fields['node-attendance_configuration-field_test'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_test',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'No' => 'No',
          'Yes' => 'Yes',
        ),
        'allowed_values_function' => '',
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => array(
        0 => array(
          'value' => 'No',
        ),
      ),
      'deleted' => '0',
      'description' => 'Select \'Yes\' to send all email messages to the test email account, usually the webmaster.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 13,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_test',
      'label' => 'Test',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '10',
      ),
    ),
  );

  // Exported field: 'node-attendance_configuration-field_test_email_address'.
  $fields['node-attendance_configuration-field_test_email_address'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_test_email_address',
      'foreign keys' => array(),
      'indexes' => array(),
      'locked' => '0',
      'module' => 'email',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '0',
      'type' => 'email',
    ),
    'field_instance' => array(
      'bundle' => 'attendance_configuration',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => 'This is email address that emails will be sent to if "Test" is set to \'Yes\'. If "Test" is set to \'No\', entries in this field will have no effect. An error will be generated if "Test" is set to "Yes" and there is no email address in this field.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'email',
          'settings' => array(),
          'type' => 'email_default',
          'weight' => 14,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_test_email_address',
      'label' => 'Test Email Address',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'email',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'email_textfield',
        'weight' => '11',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Append Policy');
  t('Attendance Admin Email');
  t('Attendance Policy');
  t('Attendance Requirement');
  t('Chapter or Club');
  t('Describe the attendance rules in detail. These may be emailed to users if violations are detected.');
  t('Enter a message here if you want to send a "Missed You" message each time the member is absent. If you leave this field blank, no message will be sent. Be sure to include your email signature.');
  t('If attendance reporting is to be emailed, enter one or more email addresses for the attendance administrators. For example, you might enter the Attendance Committee Chair\'s address and the Organization\'s President for each report.');
  t('If make-ups are allowed, they are treated in one of two ways: (1) Manual Update or (2) Automatic. <UL><LI>Manual Update: with this policy, regular meeting records are updated manually. For example, Rotary clubs allow a make-up two weeks before or two weeks after the missed meeting. In this case, the club secretary would pull up the list of meetings, select an appropriate missed meeting, and update its status from "Absent" to "Makeup". The Attendance Report will report this meeting in the Make-up column, not in the Absent column<LI>Automatic: with this policy, make-ups are added separately. The Attendance Report will report this meeting in the Make-Up column and will automatically reduce the Absent column by 1. </UL> The advantage of "Automatic" is that a full history of missed and made-up meetings is retained. The advantage of "Manual" is that you have control over make-up application.');
  t('If members are to receive a "Missed Meeting" message, should the system append the Attendance Policy to the email sent to them? This field has no effect if the "Missed Meeting" message is blank.');
  t('If you are using the "Attendance Trigger" process, select one or more status values to include in the automated member inclusion.');
  t('Make-up Policy');
  t('Makeup \'No Count\' Notation');
  t('Makeups Allowed');
  t('Makeups are reports on all reports. If they are not counted in the totals, this field contains the report annotation reminder.');
  t('Maximum Consecutive Missed Meetings');
  t('Maximum Missed Meetings');
  t('Maximum Number of Makeups allowed');
  t('Maximum number of makeups allowed during this notification period. Enter "0" if there is no set maximum or if makeup meetings are not part of your attendance policy.');
  t('Missed Email Subject - the subject of the email reminder sent to people who miss meetings.');
  t('Missed Subject');
  t('Missed You Message');
  t('Policy Date Range');
  t('Select \'Yes\' to send all email messages to the test email account, usually the webmaster.');
  t('Some organizations may have an attendance policy that discourages consecutive missed meetings. For example, if some type of Board action is required after 5 consecutive missed meetings, enter "5". When the number of consecutive missed meetings reaches 6, an email is sent to the attendance contact email address(es). Leave this field blank if this is not part of your attendance policy.');
  t('Status Inclusions');
  t('Test');
  t('Test Email Address');
  t('These fields contain the start and end date for this Attendance Policy. ');
  t('This field contains the maximum number of allowable missed meetings before Board action is required. For example, if "Attendance Requirement" is 50%, and there are 26 meetings in the notification period, then this field should contain "13" -- that is, when 13 meetings are missed, some type of board action is required.  Leave this field blank if this is not part of your attendance policy.');
  t('This field contains the percentage of total meetings required to maintain active member status. This is used for management reporting only.  Leave this field blank if you do not have a required attendance policy.');
  t('This is email address that emails will be sent to if "Test" is set to \'Yes\'. If "Test" is set to \'No\', entries in this field will have no effect. An error will be generated if "Test" is set to "Yes" and there is no email address in this field.');
  t('This is the chapter or club record that "owns" this attendance policy.');
  t('Whether or not makeups are allowed. The specific nature of makeups should be described in the "Attendance Policy".');

  return $fields;
}
